{
"renderer": {
	"bufferCount": 2,
	"syncInterval": 1,
},
"shadow": {
	"m_shadowBiasBase": 0.0001,
	"m_shadowBiasSlope": 0.001,
	"m_shadowBiasMax": 0.001,

	"m_shadowMapSize": 1024,  
	"m_shadowFarDistance": 20.0,
	"m_shadowCascadeLambda": 0.5,

	"m_shadowBehind" : 10.0,
},
"renderDebug": {
	"m_mode" : 0,
},
"window" : {
	"backbufferWidth": 1920,
	"backbufferHeight": 1080,
	"fullscreen": false,
}
}